jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # مهم عشان يقدر يعمل push
      - name: Unzip files
        run: unzip "*.zip" -d .
      - name: Remove ZIP file
        run: rm *.zip
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Unzipped files automatically" || echo "No changes to commit"
          git push
